---
title: "Virus-Motif Annotation Anyalysis"
output: html_notebook
---

## Loading annotation table

```{r}
library(ggplot2)
library(ggrepel)

#setwd('../Google Drive/00_professional/projects/FunctionalGlycanDomain/')
r = read.csv('data/glycan_motifs/lectinsVSmotifs.txt')

motifs = grep('X.G00',colnames(r),value = T)
taxa = c(' X.Genus.','X.Species.')
```

## Preview Co-occurance of Motifs
```{r}
library(gplots)
#heatmap.2( na.omit(data.matrix(r[,motifs])) , trace='none', labRow = r$X.GenomeComp.)
heatmap.2( na.omit(data.matrix(r[order(r$X.GenomeComp.),motifs])) , trace='none', labRow = r$X.GenomeComp.,Rowv = F)
```


## Initialize Genome-type variables
```{r}
r$X.GenomeComp.[r$X.GenomeComp.=='ssrna-rt'] = NA
r$ss_ds = factor( ifelse( grepl('^ds',r$X.GenomeComp.) , 'ds', ifelse(grepl('^ss',r$X.GenomeComp.), 'ss', NA)))
r$rna_dna = factor( ifelse( grepl('rna',r$X.GenomeComp.) , 'rna', ifelse(grepl('dna',r$X.GenomeComp.), 'dna', NA)))
r$neg_pos = factor( ifelse( grepl('rna\\(\\-\\)',r$X.GenomeComp.) , 'neg', ifelse(grepl('rna\\(\\+\\)',r$X.GenomeComp.), 'pos', NA)))

type = c('ss_ds','rna_dna','neg_pos')

r_orig = r
r = r_orig
r = droplevels( r[r$X.Genus. %in% names(table(r$X.Genus.))[table(r$X.Genus.)>=5],] )
```

## Compute Associations
```{r}
l=list()
for(t in type){
  for(m in motifs){
    if( length(table(r[[m]]))<2 ){next}
    tab=table(r[[t]],r[[m]],useNA = 'no')
    expected = chisq.test(tab)$expected
    attr(tab,'fisher_assumptions')= sum(tab)<1000 & all(expected>1) & (sum(expected<5)/prod(dim(expected)))>.2
    attr(tab,'chisqr_assumptions')= all(expected>1) & (sum(expected>5)/prod(dim(expected)))>.8
    l[[paste0(t,'_',m)]]=tab
  }
}
```

## Fisher Exact Test for Small Expected Values
```{r}
library(boot)
library(broom)
fisher.test.boot<-function(t_var,m_var,data,indicies){
   d <- data[indicies,]
   out=as.vector( tidy( fisher.test(table(d[[t_var]],d[[m_var]],useNA = 'no')) )[1:4] )
#   print(out)
   return(out$estimate, out$p.value)
}


fisher=do.call(rbind,lapply(names(l),function(n){
  li=l[[n]]
  if( attr(li,'fisher_assumptions')){
    print(n)
    n_split = strsplit(n,'_X')[[1]]
#    p<-boot(data=r,statistic = fisher.test.boot,R=100, t_var=n_split[1],m_var=paste0('X',n_split[2]))
    #print(paste('Pr(fisher):',
    p<-fisher.test(li)
    print(li)
    c(test='fisher',compare=paste(rownames(li),collapse='_'),selection=rownames(li)[which.max(c(li[1,2]/sum(li[1,]),li[2,2]/sum(li[2,])))],
      v1=paste(li[1,2],'/',sum(li[1,])) , v2=paste(li[2,2],'/',sum(li[2,])),stat=p$estimate,conf.low=p$conf.int[1],
      conf.high=p$conf.int[2],p.value=p$p.value,motif=strsplit(n,'\\.')[[1]][2])
  }
}))
```

## X^2 test for Non-small Expected Values
```{r}
library(boot)
library(broom)
chisq.test.boot<-function(t_var,m_var,data,indicies){
   d <- data[indicies,]
   out=chisq.test(table(d[[t_var]],d[[m_var]],useNA = 'no'))
   c(out$statistic)
   #print(out)
   #return(out)
}

chisqr=do.call(rbind,lapply(names(l),function(n){
  li=l[[n]]
  if( attr(li,'chisqr_assumptions')){
    print(n)
    p<-boot(data=r,statistic = chisq.test.boot,R=100, t_var=n_split[1],m_var=paste0('X',n_split[2]))
    ci=boot.ci(p,type='perc')
    p0<-chisq.test(li)
    print(li)
    c(test='chisqr',compare=paste(rownames(li),collapse='_'),selection=rownames(li)[which.max(c(li[1,2]/sum(li[1,]),li[2,2]/sum(li[2,])))],
      v1=paste(li[1,2],'/',sum(li[1,])) , v2=paste(li[2,2],'/',sum(li[2,])),stat=p0$statistic,conf.low=ci$percent[4],
      conf.high=ci$percent[5],p.value=p0$p.value, motif=strsplit(n,'\\.')[[1]][2])
  }
}))
```
## mixed effect models
```{r}
library(lme4)
mods=list()
for(t in c(type)){
  for(m in motifs){
    print(m)
    if(sd(r[[m]])==0){next}
    mods[[paste0(t,'_',m)]]=list( try(lm_t<-glm(as.formula(paste(m,'~',t)),data=r,family='binomial')),
                               try(lm_g<-glm(as.formula(paste(m,'~X.Genus.')),data=r,family='binomial')),
                               try(lm_s<-glm(as.formula(paste(m,'~X.Species.')),data=r,family='binomial')),
                               try(lmer_genus<-glmer(as.formula(paste(m,'~(1|X.Genus.)')),data=r,family='binomial')),
                               try(lmer_t_genus<-glmer(as.formula(paste(m,'~',t,'+(1|X.Genus.)')),data=r,family='binomial')),
                               try(lmer_genus_species<-glmer(as.formula(paste(m,'~(1|X.Genus./X.Species.)')),data=r,family='binomial')),
                               try(lmer_t_genus_species<-glmer(as.formula(paste(m,'~',t,'+(1|X.Genus./X.Species.)')),data=r,family='binomial'))
      )
  }
}

# species X motif, genus x motif
out_g_s = do.call(rbind,lapply(names(mods),function(m_n){
  m = mods[[m_n]]
  m_g = data.frame( coef(summary(m[[2]])) , confint(m[[2]]) , taxa_type='genus' )
  m_g$taxa = gsub('(Intercept)',"Influenzavirus A",gsub('X.Genus.','',rownames(m_g)))
  m_s = data.frame( coef(summary(m[[3]])) , confint(m[[3]]) , taxa_type='species')
  m_s$taxa = gsub('(Intercept)',"influenza a virus",gsub('X.Species.','',rownames(m_s)))
  df = rbind(m_g,m_s)
  df$type = strsplit( m_n,split='\\.')[[1]][1]
  df$motif = strsplit( m_n,split='\\.')[[1]][2]
  df
}))
out_g_s = unique( out_g_s[,colnames(out_g_s)!='type'] )
colnames(out_g_s) = c('Estimate','SE','z','p','lower','upper','taxa_type','taxa','motif')

#####
# species X motif, genus x motif
out_t_m = do.call(rbind,lapply(names(mods),function(m_n){
  df=NULL; m_g=NULL; m_s=NULL
  print(m_n)
  m = mods[[m_n]]
  try( df <- data.frame( coef(summary(m[[1]])) , confint(m[[1]]) , taxa_type='none' ,p_LRT=NA) )
  if(!is.data.frame(df)){return(NULL)}
  try( m_g <- data.frame( coef(summary(m[[5]])) , confint(m[[5]])[-1,] , taxa_type='genus' , p_LRT = anova(m[[4]],m[[5]],test='LRT')[2,8] ) )
  if(is.data.frame(m_g)){df = rbind(df,m_g)}
  try( m_s <- data.frame( coef(summary(m[[7]])) , confint(m[[7]])[-1,] , taxa_type='genus/species', p_LRT = anova(m[[6]],m[[7]],test='LRT')[2,8]))
  if(is.data.frame(m_s)){df = rbind(df,m_s)}
  df$type = strsplit( m_n,split='\\.')[[1]][1]
  df$motif = strsplit( m_n,split='\\.')[[1]][2]
  df
}))
colnames(out_t_m) = c('Estimate','SE','z','p','lower','upper','taxa_type','p_LRT','type','motif')
out_t_m$var = unlist( lapply( out_t_m$type[seq(1,nrow(out_t_m),2)] , function(x) strsplit(x,'_')[[1]][1:2] ))

print('done')

library(gridExtra)
library(ggrepel)
```

```{r}
dat = na.omit( out_g_s[out_g_s$upper<1e3 & out_g_s$lower>-1e3 & out_g_s$taxa_type=='genus',])
ggplot(data=dat,aes(x=taxa,y=Estimate,color=-log(p,10),label=ifelse(p<.05,motif,NA))) +
  geom_pointrange(aes(ymin = lower, ymax = upper))+ geom_hline(yintercept = 0)+
  geom_label_repel(size=2)+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+ggtitle('genus')

```

```{r}
dat = na.omit( out_g_s[out_g_s$upper<1e3 & out_g_s$lower>-1e3 & out_g_s$taxa_type=='species',])
ggplot(data=dat,aes(x=taxa,y=Estimate,color=-log(p,10),label=ifelse(p<.05,motif,NA))) +
  geom_pointrange(aes(ymin = lower, ymax = upper))+ geom_hline(yintercept = 0)+
  geom_label_repel(size=2)+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+ggtitle('species')
```
```{r}
dat = droplevels(unique( out_t_m[ is.finite(out_t_m$lower) & is.finite(out_t_m$upper) & out_t_m$lower>(-100) & out_t_m$upper<100 ,] ))
ggplot(data=dat[dat$taxa_type=='genus',],aes(x=var,y=Estimate,color=-log(p_LRT,10))) +
  geom_pointrange(aes(ymin = lower, ymax = upper))+ geom_hline(yintercept = 0)+ facet_wrap(~motif+type,scales = 'free')+
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) #+ggtitle('GLMM controlling for genus') 
```


```{r}
#dat = droplevels(unique( out_t_m[!grepl('(Intercept)',rownames(out_t_m)) & is.finite(out_t_m$lower) & is.finite(out_t_m$upper) ,] ))
#ggplot(data=dat[dat$taxa_type=='none',],aes(x=motif,y=Estimate,color=-log(p,10),shape=type)) +
#  geom_pointrange(aes(ymin = lower, ymax = upper))+ geom_hline(yintercept = 0)+
#  theme(axis.text.x = element_text(angle = 45, hjust = 1))+ggtitle('GLM') 

dat = droplevels(unique( out_t_m[ is.finite(out_t_m$lower) & is.finite(out_t_m$upper) & out_t_m$lower>(-100) & out_t_m$upper<100 ,] ))
ggplot(data=dat[dat$taxa_type=='none',],aes(x=var,y=Estimate,color=-log(p,10),shape=type)) +
  geom_pointrange(aes(ymin = lower, ymax = upper))+ geom_hline(yintercept = 0)+ facet_wrap(~motif,scales = 'free')+
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) #+ggtitle('GLMM controlling for genus') 
```

## Save to xlsx
```{r}
out = rbind(fisher,chisqr)
out = out[order(out[,'motif']),]

library(openxlsx)

write.xlsx(out,file = 'annotation/virus_motif.xlsx')
write.xlsx(out_g_s,file = 'annotation/virus_genus_species_motif.xlsx')
write.xlsx(out_t_m,file = 'annotation/virus_genome_taxaControlled_motif.xlsx')

```

